tasks:
  - before: npm install -g npm eslint prettier @vue/cli
    init: npm install
    command: npm audit fix
  - command: npm run serve -- --port 3000
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - mikestead.dotenv
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - octref.vetur
    - oderwat.indent-rainbow
    - coenraads.bracket-pair-colorizer-2
    - christian-kohler.path-intellisense
    - davidanson.vscode-markdownlint